### ISSUE TITLE
Boleh minta database kosa kata bahasa Indonesia?

### ISSUE THREAD

**Issue by gyot** [yukuku/kbbi4#7]
Saya dan teman-teman komunitas budaya di Lombok Provinsi NTB ingin membuat kamus bahasa sasak Halus, boleh kami minta database kosa kata bahasa Indonesianya?

**Comment by yukuku** [comment]
Coba hubungi pihak penyedia KBBI, misalnya Winda Luthfita <windaluthfita@gmail.com>

**Comment by gyot** [comment]
> Coba hubungi pihak penyedia KBBI, misalnya Winda Luthfita [windaluthfita@gmail.com](mailto:windaluthfita@gmail.com)

Terimakasih banyak
